// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVoufo6S8_DNNL6CDy29hGAgV7epLAhi4',
    appId: '1:583400146216:web:d37fc04e0c6ed8fa4e3c1d',
    messagingSenderId: '583400146216',
    projectId: 'focusflow-2026',
    authDomain: 'focusflow-2026.firebaseapp.com',
    storageBucket: 'focusflow-2026.firebasestorage.app',
    measurementId: 'G-9JXG18CC2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3KCN3JYa3O3KHBIJwLBvnUiwwfbU0G8E',
    appId: '1:583400146216:android:d2e6ade84cfefd864e3c1d',
    messagingSenderId: '583400146216',
    projectId: 'focusflow-2026',
    storageBucket: 'focusflow-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVoufo6S8_DNNL6CDy29hGAgV7epLAhi4',
    appId: '1:583400146216:web:0c940333a3b92b144e3c1d',
    messagingSenderId: '583400146216',
    projectId: 'focusflow-2026',
    authDomain: 'focusflow-2026.firebaseapp.com',
    storageBucket: 'focusflow-2026.firebasestorage.app',
    measurementId: 'G-8MMP02P6XC',
  );
}
